### PR TITLE
refactor: refactored... everything!

### PR DESCRIPTION
**Pull request by anuraghazra**
I refactored most of the code, 90% code reduced! Yey! :100: :partying_face:

### CODE REVIEW

**Comment by prvnbist** [comment]
Thanks for the awesome work @anuraghazra, I'll review and get back to you🙌🏼

**Comment by prvnbist** [comment]
I'd like to suggest a few things:
1. Let's move utils files into utils folder at `/src/utils`
2. Rename the `Transform.jsx` file to `Editor.jsx` and move it to sections folder since it doesnt fit in with the pages anymore.
3. We can also move the code inside `editor.js` into now `Editor.jsx` file in sections folder since the editor code isnt repeated for each page anymore.

With the approach you took in the PR, it made the project really scalable in terms of adding more tools. Major props to that.

**Comment by anuraghazra** [comment]
Okay! I'll push the changes tomorrow 😃

**Comment by anuraghazra** [comment]
@prvnbist pushed the updates, please review the changes.

**Pull request merged**
